In [1]:
import numpy as np
import pandas as pd

### Question 1: Pandas Version

In [2]:
pd.__version__

'2.0.3'

### Getting the California Housing Prices Dataset

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 18:16:40--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.01s   

2023-09-18 18:16:40 (112 MB/s) - ‘housing.csv’ saved [1423529/1423529]



### Question 2: How many columns are in the dataset?

In [5]:
df = pd.read_csv("housing.csv")
df.head(n=3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [11]:
print(f"The number of columns in the dataframe are: {df.shape[1]} ")

The number of columns in the dataframe are: 10 


### Question 3: Which columns in the dataset have missing values?

In [12]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

In [20]:
print(f"The column(s) in the dataset with missing values is: {df.columns[df.isnull().any()][0]} ")

The column(s) in the dataset with missing values is: total_bedrooms 


### Question 4: How many unique values does the ocean_proximity column have?

In [24]:
uniq = df.ocean_proximity.nunique()
print(f"ocean_proximity column has {uniq} unique values ")

ocean_proximity column has 5 unique values 


### Question 5: What's the average value of the median_house_value for the houses located near the bay?

In [36]:
avg_value = df[df['ocean_proximity'] == 'NEAR BAY'] \
                .median_house_value.mean()
print(f"The average value of the median_house_value for the houses located near the bay is: {int(avg_value)} ")

The average value of the median_house_value for the houses located near the bay is: 259212 


### Question 6
1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

In [37]:
# Step 1: Calculate the average of total_bedrooms column in the dataset. 
avg_total_bedrooms = df.total_bedrooms.mean()
avg_total_bedrooms

537.8705525375618

In [38]:
# Step 2: Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df["total_bedrooms"].fillna(avg_total_bedrooms,inplace=True)

In [39]:
# Step 3: Now, calculate the average of total_bedrooms again.
df.total_bedrooms.mean()

537.8705525375617

Step 4: The Average of total_bedrooms column has not changed. We can confirm that the missing values have been replaced. We notice that no column (especially total_bedrooms) has no missing values. 

In [40]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

### Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

In [50]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [51]:
# Step 1: Select all the options located on islands.
df_islands = df[df['ocean_proximity'] == "ISLAND"]
df_islands

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [52]:
# Step 2: Select only columns housing_median_age, total_rooms, total_bedrooms.
df_islands = df_islands[['housing_median_age','total_rooms','total_bedrooms']]
df_islands

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [53]:
# Step 3: Get the underlying NumPy array. Let's call it X.
X = df_islands.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [54]:
# Step 4: Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. 
# Let's call the result XTX.
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [56]:
# Step 5: Compute the inverse of XTX.
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [61]:
# Step 6: Create an array y with values [950, 1300, 800, 1000, 1300].
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [63]:
# Step 7: Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inverse.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [66]:
# Step 8: What's the value of the last element of w?
print(f"The last element of w is {w[-1].round(4)}")

The last element of w is 5.6992
